package comparisonOperator

import com.itheima.drools.entity.ComparisonOperatorEntity

//测试比较操作符contains
rule "rule_comparison_contains"
    when
        ComparisonOperatorEntity(names contains "张三")
        ComparisonOperatorEntity(list contains names)
    then
        System.out.println("规则: rule_comparison_contains触发了...");
end

//测试比较操作符not contains
rule "rule_comparison_not_contains"
    when
        ComparisonOperatorEntity(names not contains "张三")
        ComparisonOperatorEntity(list not contains names)
    then
        System.out.println("规则: rule_comparison_not_contains触发了...");
end

//测试比较操作符memberOf
rule "rule_comparison_memberOf"
    when
        ComparisonOperatorEntity(names memberOf list)
    then
        System.out.println("规则: rule_comparison_memberOf触发了...");
end

//测试比较操作符not memberOf
rule "rule_comparison_not_memberOf"
    when
        ComparisonOperatorEntity(names not memberOf list)
    then
        System.out.println("规则: rule_comparison_not_memberOf触发了...");
end

//测试比较操作符matches
rule "rule_comparison_matches"
    when
        ComparisonOperatorEntity(names matches "王.*")
    then
        System.out.println("规则: rule_comparison_matches触发了...");
end

//测试比较操作符not matches
rule "rule_comparison_not_matches"
    when
        ComparisonOperatorEntity(names not matches "王.*")
    then
        System.out.println("规则: rule_comparison_not_matches触发了...");
end