package testlhs

import com.itheima.drools.entity.Student

rule "rule_lhs_1"
    when
        $s:Student(name in ("张三", "李四", "王五"))
    then
        System.out.println("规则: rule_lhs_1触发了...");
end

rule "rule_lhs_2"
    when
        $s:Student(name not in ("张三", "李四", "王五"))
    then
        System.out.println("规则: rule_lhs_2触发了...");
end

rule "rule_lhs_3"
    when
        eval(1 == 1)
    then
        System.out.println("规则: rule_lhs_3触发了...");
end

rule "rule_lhs_4"
    when
        not Student()
    then
        System.out.println("规则: rule_lhs_4触发了...");
end

rule "rule_lhs_5"
    when
        exists Student()
    then
        System.out.println("规则: rule_lhs_5触发了...");
end

rule "rule_lhs_6"
    when
        Student()
    then
        System.out.println("规则: rule_lhs_6触发了...");
end

rule "rule_lhs_7"
    when
        Student(age > 10)
    then
        System.out.println("规则: rule_lhs_7触发了...");
end

rule "rule_lhs_8" extends "rule_lhs_7"
    when
        Student(age < 20)
    then
        System.out.println("规则: rule_lhs_8触发了...");
end